# -*- mode: ruby -*
# vi: set ft=ruby :


BOX_IMAGE = "sbeliakou/centos"

[["zabbix-srv21","192.168.56.21"], ["zabbix-ag21","192.168.56.22"]].each do |te|


 Vagrant.configure("2") do |config|

    config.vm.define te[0] do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = te[0]
      subconfig.vm.network :private_network, ip: te[1]
      subconfig.vm.provider "virtualbox" do |vb|
        vb.name = te[0]
        vb.memory = "768"
      end
      subconfig.vm.provision "shell", path: "provision.sh"
    end

 end

end